-- Create the settings table to store global configurations
CREATE TABLE IF NOT EXISTS public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  payload jsonb
);

-- Create the students table to store all student data, scores, and enrolment info
CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  payload jsonb
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- Replace policies on public.settings (idempotent)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.settings;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.settings;

CREATE POLICY "Enable read access for all users" ON public.settings
  FOR SELECT
  USING (true);

CREATE POLICY "Enable insert access for all users" ON public.settings
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.settings
  FOR UPDATE
  USING (true);

-- Replace policies on public.students (idempotent)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.students;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.students;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.students;
DROP POLICY IF EXISTS "Enable delete access for all users" ON public.students;

CREATE POLICY "Enable read access for all users" ON public.students
  FOR SELECT
  USING (true);

CREATE POLICY "Enable insert access for all users" ON public.students
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.students
  FOR UPDATE
  USING (true);

CREATE POLICY "Enable delete access for all users" ON public.students
  FOR DELETE
  USING (true);

-- Initialize default settings row so the app loads correctly on first run
INSERT INTO public.settings (id, payload)
VALUES (1, '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;